function RFL(givenList) 
{ // Returns a random value from a list
return givenList[Math.floor(Math.random() * givenList.length)];
}
function Gen()
{
    for(let i = 0; i < 6; i++)
{
    
    const instruments = 
    [
        "Woodwind - Winds",
        "Woodwind - Piccolo",
        "Woodwind - Flute",
        "Woodwind - Danso",
        "Woodwind - Irish Flute",
        "Woodwind - Traverso",
        "Woodwind - Dizi",
        "Woodwind - Shakuhachi",
        "Woodwind - Fife",
        "Woodwind - Tin Whistle",
        "Woodwind - Slide Whistle",
        "Woodwind - French Flageolet",
        "Woodwind - English Flageolet",
        "Woodwind - Garklein Recorder",
        "Woodwind - Recorder",
        "Woodwind - Ocarina",
        "Woodwind - Gemshorn",
        "Woodwind - Pan Flute",
        "Woodwind - Quena",
        "Woodwind - Oboe",
        "Woodwind - English Horn",
        "Woodwind - Heckelphone",
        "Woodwind - Lupophone",
        "Woodwind - Shawm",
        "Woodwind - Cromorne",
        "Woodwind - Crumhorn",
        "Woodwind - Comamuse",
        "Woodwind - Kelhorn",
        "Woodwind - Rauschpfeife",
        "Woodwind - Duduk",
        "Woodwind - Shenai",
        "Woodwind - Clarinet",
        "Woodwind - Chalumeau",
        "Woodwind - Pocket Sax",
        "Woodwind - Tarogato",
        "Woodwind - Octavin",
        "Woodwind - Saxophone",
        "Woodwind - Aulochrome",
        "Woodwind - Bassoon",
        "Woodwind - Contrabassoon",
        "Woodwind - Dulcian",
        "Woodwind - Rackett",
        "Woodwind - Sarrusophone",
        "Woodwind - Bagpipe",
        "Free Reed - Accordion",
        "Free Reed - Bandoneon",
        "Free Reed - Concertina",
        "Free Reed - Harmonica",
        "Free Reed - Melodica",
        "Free Reed - Sheng",
        "Brass - Brass Section",
        "Brass - Horn",
        "Brass - Vienna Horn",
        "Brass - Wagner Tuba",
        "Brass - Cornet",
        "Brass - Saxhorn",
        "Brass - Posthorn",
        "Brass - Piccolo Trumpet",
        "Brass - Trumpet",
        "Brass - Pocket Trumpet",
        "Brass - Slide Trumpet",
        "Brass - Bugle",
        "Brass - Mellophone",
        "Brass - Fiscorn",
        "Brass - Flugelhorn",
        "Brass - Kuhlohorn",
        "Brass - Ophicleide",
        "Brass - Serpent",
        "Brass - Trombone",
        "Brass - Cimbasso",
        "Brass - Sackbut",
        "Brass - Euphonium",
        "Brass - Tuba",
        "Brass - Sousaphone",
        "Brass - Helicon",
        "Brass - Conch",
        "Brass - Horagai",
        "Brass - Alphorn",
        "Brass - Rag Dung",
        "Brass - Didgeridoo",
        "Brass - Shofar",
        "Brass - Vuvuzela",
        "Pitched Percussion - Timpani",
        "Pitched Percussion - Roto-Toms",
        "Pitched Percussion - Tubaphone",
        "Pitched Percussion - Steel Drums",
        "Pitched Percussion - Glockenspiel",
        "Pitched Percussion - Xylophone",
        "Pitched Percussion - Xylomarimba",
        "Pitched Percussion - Vibraphone",
        "Pitched Percussion - Dulcimer",
        "Pitched Percussion - Cimbalom",
        "Pitched Percussion - Marimba",
        "Pitched Percussion - Crotales",
        "Pitched Percussion - Almglocken",
        "Pitched Percussion - Chimes",
        "Pitched Percussion - Carillon",
        "Pitched Percussion - Tuned Gongs",
        "Pitched Percussion - Handbells",
        "Pitched Percussion - Handchimes",
        "Pitched Percussion - Flexatone",
        "Pitched Percussion - Musical Saw",
        "Pitched Percussion - Musical Glasses",
        "Pitched Percussion - Glass Harmonica",
        "Pitched Percussion - Tuned Klaxon Horns",
        "Pitched Percussion - Kalimba",
        "Vocals - Soprano",
        "Vocals - Mezzo-Soprano",
        "Vocals - Countertenor",
        "Vocals - Alto",
        "Vocals - Contralto",
        "Vocals - Tenor",
        "Vocals - Baritone",
        "Vocals - Voice",
        "Vocals - Bass",
        "Vocals - Women",
        "Vocals - Men",
        "Vocals - Kazoo",
        "Keyboard - Celesta",
        "Keyboard - Clavichord",
        "Keyboard - Clavinet",
        "Keyboard - Harpsichord",
        "Keyboard - Virginal",
        "Keyboard - Electric Piano",
        "Keyboard - Grand Piano",
        "Keyboard - Honky Tonk Piano",
        "Keyboard - Piano",
        "Keyboard - Toy Piano",
        "Keyboard - Upright Piano",
        "Keyboard - Hammond Piano",
        "Keyboard - Organ",
        "Keyboard - Percussive Organ",
        "Keyboard - Pipe Organ",
        "Keyboard - Rotary Organ",
        "Keyboard - Harmonium",
        "Keyboard - Reed Organ",
        "Electronic - Mallet Synth",
        "Electronic - Ondes Martenot",
        "Electronic - Atmosphere Synth",
        "Electronic - Bass Synth",
        "Electronic - Bowed Synth",
        "Electronic - Brass Synth",
        "Electronic - Brightness Synth",
        "Electronic - Choir Synth",
        "Electronic - Crystal Synth",
        "Electronic - Echoes Synth",
        "Electronic - Effect Synth",
        "Electronic - Goblins Synth",
        "Electronic - Halo Synth",
        "Electronic - Metallic Synth",
        "Electronic - New Age Synth",
        "Electronic - Pad Synth",
        "Electronic - Poly Synth",
        "Electronic - Rain Synth",
        "Electronic - Saw Synth",
        "Electronic - Sci-Fi Synth",
        "Electronic - Sine Synth",
        "Electronic - Soundtrack Synth",
        "Electronic - Square Synth",
        "Electronic - String Synth",
        "Electronic - Sweep Theramin",
        "Electronic - Warm Synth",
        "Plucked String - Harp",
        "Plucked String - Cavaquinho",
        "Plucked String - Guitar",
        "Plucked String - Electric Bass",
        "Plucked String - Bass Guitar",
        "Plucked String - Banjo",
        "Plucked String - Irish Banjo",
        "Plucked String - Ukulele",
        "Plucked String - Mandolin",
        "Plucked String - Mtn. Dulcimer",
        "Plucked String - Lute",
        "Plucked String - Theorbo",
        "Plucked String - Archlute",
        "Plucked String - Balalaika",
        "Plucked String - Bouzouki",
        "Plucked String - Guzheng",
        "Plucked String - Koto",
        "Plucked String - Oud",
        "Plucked String - Shamisen",
        "Plucked String - Sitar",
        "Plucked String - Prim",
        "Plucked String - Brac",
        "Plucked String - Bulgarija",
        "Plucked String - Berda",
        "Plucked String - Celo",
        "Plucked String - Bandurria",
        "Plucked String - Laud",
        "Plucked String - Canario",
        "Bowed String - Strings",
        "Bowed String - Violin",
        "Bowed String - Viola",
        "Bowed String - Violoncello",
        "Bowed String - Contrabass",
        "Bowed String - Viol",
        "Bowed String - Baryton",
        "Bowed String - Violone",
        "Bowed String - Octobass",
        "Bowed String - Pardessus De Viole",
        "Bowed String - Erhu",
        "Bowed String - Nyckelharpa",
        "Bowed String - Cello"
    ];
    const percInstruments = 
    [
        "Pitched Percussion - Timpani",
        "Pitched Percussion - Roto-Toms",
        "Pitched Percussion - Tubaphone",
        "Pitched Percussion - Steel Drums",
        "Pitched Percussion - Glockenspiel",
        "Pitched Percussion - Xylophone",
        "Pitched Percussion - Xylomarimba",
        "Pitched Percussion - Vibraphone",
        "Pitched Percussion - Dulcimer",
        "Pitched Percussion - Cimbalom",
        "Pitched Percussion - Marimba",
        "Pitched Percussion - Crotales",
        "Pitched Percussion - Almglocken",
        "Pitched Percussion - Chimes",
        "Pitched Percussion - Carillon",
        "Pitched Percussion - Tuned Gongs",
        "Pitched Percussion - Handbells",
        "Pitched Percussion - Handchimes",
        "Pitched Percussion - Flexatone",
        "Pitched Percussion - Musical Saw",
        "Pitched Percussion - Musical Glasses",
        "Pitched Percussion - Glass Harmonica",
        "Pitched Percussion - Tuned Klaxon Horns",
        "Pitched Percussion - Kalimba",
        "Unpitched Percussion - Automobile Brake Drums",
        "Unpitched Percussion - Bongos",
        "Unpitched Percussion - Janggu",
        "Unpitched Percussion - Ko-Tsuzumi",
        "Unpitched Percussion - O-Tsuzumi",
        "Unpitched Percussion - Chinese Tom-Toms",
        "Unpitched Percussion - Sogo",
        "Unpitched Percussion - Bass Drum",
        "Unpitched Percussion - Okedo-Daiko",
        "Unpitched Percussion - Snare Drum",
        "Unpitched Percussion - Concert Toms",
        "Unpitched Percussion - Congas",
        "Unpitched Percussion - Shime-Daiko",
        "Unpitched Percussion - Kakko",
        "Unpitched Percussion - Xiaogu",
        "Unpitched Percussion - Doumbek",
        "Unpitched Percussion - Djembe",
        "Unpitched Percussion - Cajon",
        "Unpitched Percussion - Cuica",
        "Unpitched Percussion - Field Drum",
        "Unpitched Percussion - Frame Drum",
        "Unpitched Percussion - Bangu",
        "Unpitched Percussion - Piccolo Snare",
        "Unpitched Percussion - Slit Drum",
        "Unpitched Percussion - Tablas",
        "Unpitched Percussion - Timbales",
        "Unpitched Percussion - Buk",
        "Unpitched Percussion - Taiko",
        "Unpitched Percussion - Tsuri-Daiko",
        "Unpitched Percussion - Miya-Daiko",
        "Unpitched Percussion - Dagu",
        "Unpitched Percussion - Anvil",
        "Unpitched Percussion - Shoko",
        "Unpitched Percussion - Kane",
        "Unpitched Percussion - Bell Plate",
        "Unpitched Percussion - Bell Tree",
        "Unpitched Percussion - Bowl Gongs",
        "Unpitched Percussion - Chains",
        "Unpitched Percussion - China Cymbal",
        "Unpitched Percussion - Opera Gong",
        "Unpitched Percussion - Wind Gong",
        "Unpitched Percussion - Daluo",
        "Unpitched Percussion - Xiaoluo",
        "Unpitched Percussion - Dabo",
        "Unpitched Percussion - Naobo",
        "Unpitched Percussion - Kkwaenggwari",
        "Unpitched Percussion - Cowbell",
        "Unpitched Percussion - Agogo Bells",
        "Unpitched Percussion - Suspended Cymbal",
        "Unpitched Percussion - Hand Cymbal",
        "Unpitched Percussion - Finger Cymbal",
        "Unpitched Percussion - Hi-Hat",
        "Unpitched Percussion - Iron Pipes",
        "Unpitched Percussion - Mark Tree",
        "Unpitched Percussion - Metal Castanets",
        "Unpitched Percussion - Metal Wind Castanets",
        "Unpitched Percussion - Ride Cymbal",
        "Unpitched Percussion - Sleigh Bells",
        "Unpitched Percussion - Splash Cymbal",
        "Unpitched Percussion - Tam-Tam",
        "Unpitched Percussion - Jing",
        "Unpitched Percussion - Thundersheet",
        "Unpitched Percussion - Triangle",
        "Unpitched Percussion - Bamboo wind Chimes",
        "Unpitched Percussion - Castanets",
        "Unpitched Percussion - Claves",
        "Unpitched Percussion - Ban",
        "Unpitched Percussion - Guiro",
        "Unpitched Percussion - Temple Blocks",
        "Unpitched Percussion - Log Drum",
        "Unpitched Percussion - Wood Blocks",
        "Unpitched Percussion - Bangzi",
        "Unpitched Percussion - Wooden Wind Chimes",
        "Unpitched Percussion - Cabasa",
        "Unpitched Percussion - Glass Wind Chimes",
        "Unpitched Percussion - Maracas",
        "Unpitched Percussion - Quijada",
        "Unpitched Percussion - Ratchet",
        "Unpitched Percussion - Sandpaper Blocks",
        "Unpitched Percussion - Shaker",
        "Unpitched Percussion - Shakere",
        "Unpitched Percussion - Shell Wind Chimes",
        "Unpitched Percussion - Stones",
        "Unpitched Percussion - Tambourine",
        "Unpitched Percussion - Tubo",
        "Unpitched Percussion - Vibraslap",
        "Unpitched Percussion - Whip",
        "Unpitched Percussion - Cannon",
        "Unpitched Percussion - Bird Call",
        "Unpitched Percussion - Ocean Drum",
        "Unpitched Percussion - MIDI",
        "Marching Percussion - Marching Snare",
        "Marching Percussion - Marching Tenor Drums",
        "Marching Percussion - Show-Style Drums",
        "Marching Percussion - Marching Bass Drums",
        "Marching Percussion - Marching Cymbals",
        "Body Percussion - Finger Snap",
        "Body Percussion - Hand Clap",
        "Body Percussion - Slap",
        "Body Percussion - Stamp"
    ]
    document.getElementById(i.toString()).innerHTML = RFL(instruments);
    document.getElementById("p").innerHTML = RFL(percInstruments);
}
}
